name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: plannify-truck-driver/github-actions/.github/workflows/build-push-tag.yml@main
    secrets: inherit
    with:
      use_gitleaks: false
      use_sast: false
      images: |
        [
          {"image": "plannify-truck-driver/website"}
        ]
      infra_targets: |
        [
          {"repo": "plannify-truck-driver-app/infrastructure", "file": "yaml-applications/prod/website/deployment.yaml", "image": "ghcr.io/plannify-truck-driver/website"}
        ]
